### ISSUE TITLE
function problem

### ISSUE THREAD

**Issue by MZJR** [osu-youa/ur-arm-utils#1]
I'm a newbie, could you tell me how to use this feature pack？Should I write my own program to send commands to those ROSservice?

**Comment by osu-youa** [comment]
Yup, you'll want to interact with the provided files through the corresponding ROS services. You may want to look at [sample.py](https://github.com/osu-youa/ur-arm-utils/blob/main/scripts/sample.py) for some example usages.

**Comment by MZJR** [comment]
Thanks for your quick reply, I will try further.
